# 项目相关配置
system:
  # 项目名称
  name: init
  # 开发者
  developer: 张庆福
  # 版本
  version: 0.0.1

server:
  servlet:
    # 项目路径前缀
    context-path: /@artifactId@
spring:
  profiles:
    # 指定运行环境
    active: @profiles.active@
  application:
    # 指定服务名称
    name: @artifactId@
  servlet:
    # 文件上传
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 总上传的文件大小
      max-request-size: 20MB
  # jackson时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

mybatis-plus:
  # 指定Mapper.xml文件位置,可以是数组
  mapperLocations: classpath*:/mapper/**/*.xml
  configuration:
    # sql输出设置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用带包名
  typeAliasesPackage: com.example.*.entity
  global-config:
    db-config:
      # 配置逻辑删除相关
      # 全局逻辑删除的实体字段名(根据实际情况配置)
      logic-delete-field: del
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1

knife4j:
  # 开启增强功能
  enable: true

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# 获取pom中的值
app:
  version: @project.version@